#!/bin/bash
echo $0
echo $1 $2 $3 $4 $5 $6 $7 $8
echo "===========Number of arguments in Bash Script=================="
echo $#
echo "===========Number of arguments supplied======================="
echo $@
echo "===============Process id====================================="
echo $$
